### ISSUE TITLE
MetaDrive version is out of date.

### ISSUE THREAD

**Issue by YYan99** [jjyyxx/srlnbc#1]
This repository needs MetaDrive-0.2.6.0, but the latest MetaDrive version is 0.3.0.1. Installing the latest MetaDrive will occur some errors.

**Comment by jjyyxx** [comment]
Thanks for your attention to this project. We have no plan to upgrade our dependencies and will keep this repository as is. If you wish to use newer MetaDrive, you could investigate our MetaDrive wrapper for any incompatibility.
