### ISSUE TITLE
How sample_batch[CostPostprocessing.FEASIBLE] and sample_batch[CostPostprocessing.INFEASIBLE] are updated in the trainer?

### ISSUE THREAD

**Issue by zzjun725** [jjyyxx/srlnbc#2]
Hi, 

Thanks for the outstanding work. 
After going through the code I am a little confused about the post-processing part. In the postprocess function provided here(https://github.com/jjyyxx/srlnbc/blob/main/srlnbc/agents/safety/ppo_barrier/ppo_barrier_tf_policy.py#L90), sample_batch[CostPostprocessing.FEASIBLE] and sample_batch[CostPostprocessing.INFEASIBLE] are not presented, which are later been used in the loss function. I tried to search for the keyword but still can't find where those info are updated so far. 
Did I miss something here? Thank you in advance!

**Comment by yangyujie-jack** [comment]
Hi, sorry for the late reply. These two keys are updated in the function `gather_from_info()`, which is called at the very beginning of `postprocess()`:
https://github.com/jjyyxx/srlnbc/blob/4d2217b833e62e40f8a401a09b2283493e7e9958/srlnbc/agents/safety/ppo_barrier/ppo_barrier_tf_policy.py#L91-L97
The function `gather_from_info()` takes the values of specified keys from `input_dict[SampleBatch.INFOS]` to `input_dict`, details can be found at:
https://github.com/jjyyxx/srlnbc/blob/4d2217b833e62e40f8a401a09b2283493e7e9958/srlnbc/agents/safety/mixin.py#L63

**Comment by zzjun725** [comment]
I will check that, thanks for the reply!
